[target.i686-pc-windows-gnu]
image = "rustembedded/cross:i686-pc-windows-gnu"

[target.i686-unknown-linux-gnu]
image = "auxlua/i686-unknown-linux-gnu"

[build.env]
passthrough = [
	"PKG_CONFIG_ALLOW_CROSS"
]

